name: 'Setup YugabyteDB'
description: 'Github action to setup a YugabyteDB'
author: 'yugabyte'
branding:
  icon: 'database'
  color: 'purple'
inputs:
  yb_image_tag:
    required: false
    description: 'Docker yugabytedb image tag. For available image tags please see https://hub.docker.com/r/yugabytedb/yugabyte'
    default: 'latest'
  yb_master_ui_port:
    description: 'YB Master UI'
    required: false
    default: '7000'
  yb_tserver_ui_port:
    description: 'YB Tserver UI'
    required: false
    default: '9000'
  ysql_port:
    description: 'YSQL API Port'
    required: false
    default: '5433'
  ycql_port:
    description: 'YCQL API Port'
    required: false
    default: '9042'
  ysql_user:
    description: 'YSQL User'
    required: false
  ysql_password:
    description: 'YSQL Password, Setting this will enable the authentication mode'
    required: false
  ysql_db:
    description: 'YSQL DB'
    required: false
  ycql_user:
    description: 'YCQL User, Setting this will enable the authentication mode'
    required: false
  ycql_password:
    description: 'YCQL Password, Setting this will enable the authentication mode'
    required: false
  ycql_keyspace:
    description: 'YCQL Keyspace'
    required: false
outputs:
  container_id: # id of output
    description: 'Container ID'
  yb_master_ui_port:
    description: 'YB Master UI'
  yb_tserver_ui_port:
    description: 'YB Tserver UI'
  ysql_port:
    description: 'YSQL API Port'
  ycql_port:
    description: 'YCQL API Port'
runs:
  using: 'docker'
  image: 'Dockerfile'
